/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnonymousHome: typeof import('./views/AnonymousHome.vue')['default']
    CardTabStorages: typeof import('./components/card/TabStorages.vue')['default']
    CardUserProfile: typeof import('./components/card/UserProfile.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LayoutsDefaultLayout: typeof import('./views/layouts/DefaultLayout.vue')['default']
    LayoutsNaviMenu: typeof import('./views/layouts/NaviMenu.vue')['default']
    LayoutsOtherLayout: typeof import('./views/layouts/OtherLayout.vue')['default']
    LayoutsToolbarBasic: typeof import('./views/layouts/ToolbarBasic.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH4: typeof import('naive-ui')['NH4']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NPopover: typeof import('naive-ui')['NPopover']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopHomeView: typeof import('./views/shop/HomeView.vue')['default']
    TableCollectItem: typeof import('./components/table/CollectItem.vue')['default']
    TableOrderCollect: typeof import('./components/table/OrderCollect.vue')['default']
  }
}
